package com.aeeventos.core.bean;



import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.aeeventos.core.bean.enums.EstadoEventoEnum;
import com.aeeventos.core.dao.EventoHome;



/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEvento;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private Date fecha;
	private Date fechaCierre;
	private EstadoEventoEnum estadoEvento;
	private Boolean borrado;
	private Boolean pago;
	private String contexto;
	private Set<Acreditacion> acreditacions = new HashSet<Acreditacion>(0);


	public Evento() {
		this.pago = null;
	}

	public Evento(int idEvento, Usuario usuario, String nombre, Date fecha,
			Date fechaCierre, EstadoEventoEnum estadoEvento, Boolean borrado,
			 Boolean pago) {
		this.idEvento = idEvento;
		this.usuario = usuario;
		this.nombre = nombre;
		this.fecha = fecha;
		this.fechaCierre = fechaCierre;
		this.estadoEvento = estadoEvento;
		this.borrado = borrado;
		this.pago = pago;
	}

	public Evento(int idEvento, Usuario usuario, String nombre,
			String descripcion, Date fecha, Date fechaCierre, EstadoEventoEnum estadoEvento,
			Boolean borrado,Boolean pago,
			String contexto, Set<Acreditacion> acreditacions,
			Set<Acreditacion> acreditacions_1,
			Set<Acreditacion> acreditacions_2, Set<Acreditacion> acreditacions_3) {
		this.idEvento = idEvento;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.fechaCierre = fechaCierre;
		this.estadoEvento = estadoEvento;
		this.borrado = borrado;
		this.pago = pago;
		this.contexto = contexto;
		this.acreditacions = acreditacions;

	}

	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaCierre() {
		
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public EstadoEventoEnum getEstadoEvento() {
		return this.estadoEvento;
	}

	public void setEstadoEvento(EstadoEventoEnum estadoEvento) {
		this.estadoEvento = estadoEvento;
	}

	public Boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(Boolean borrado) {
		this.borrado = borrado;
	}
	
	public Boolean isPago() {
		return this.pago;
	}

	public void setPago(Boolean pago) {
		this.pago = pago;
	}

	public String getContexto() {
		return this.contexto;
	}

	public void setContexto(String contexto) {
		this.contexto = contexto;
	}

	public Set<Acreditacion> getAcreditacions() {
		return this.acreditacions;
	}

	public void setAcreditacions(Set<Acreditacion> acreditacions) {
		this.acreditacions = acreditacions;
	}
	
	public static List<Evento> getAll()  {
		return EventoHome.getInstance().findAll();
	}
	
	public static List<Evento> findByExampleUsuario(Evento evt)  {
		return EventoHome.getInstance().findByExampleUsuario(evt);
	}
	
	public static Evento findById(int idEvento) {
		return EventoHome.getInstance().findById(idEvento);
	}
	public static List<Evento> findByExample(Evento evt)  {
		return EventoHome.getInstance().findByExample(evt);
	}
	
	public static void update(Evento evt)
	{
		EventoHome.getInstance().update(evt);
	}

	
	
	
	

}
