package aeeventos.core.bean;

// Generated Aug 19, 2009 5:01:06 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.exception.ConstraintViolationException;

import aeeventos.core.dao.AsistenteHome;

/**
 * Asistente generated by hbm2java
 */
public class Asistente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAsistente;
	private String apellido;
	private String nombre;
	private String telefono;
	private String celular;
	private String fax;
	private String direccion;
	private String ciudad;
	private Integer referencia;
	private String usuarioInsert;
	private String usuarioUpdate;
	private Date fechaInsert;
	private Date fechaUpdate;
	private String cargo;
	private String compania;
	private String email;
	private String dni;
	private Set<Acreditacion> acreditacions = new HashSet<Acreditacion>(0);

	public Asistente() {
	}

	public Asistente(int idAsistente, String apellido, String nombre,
			String telefono, String usuarioInsert, String usuarioUpdate,
			Date fechaInsert, Date fechaUpdate, String cargo, String compania) {
		this.idAsistente = idAsistente;
		this.apellido = apellido;
		this.nombre = nombre;
		this.telefono = telefono;
		this.usuarioInsert = usuarioInsert;
		this.usuarioUpdate = usuarioUpdate;
		this.fechaInsert = fechaInsert;
		this.fechaUpdate = fechaUpdate;
		this.cargo = cargo;
		this.compania = compania;
	}

	public Asistente(int idAsistente, String apellido, String nombre,
			String telefono, String celular, String fax, String direccion,
			String ciudad, Integer referencia, String usuarioInsert,
			String usuarioUpdate, Date fechaInsert, Date fechaUpdate,
			String cargo, String compania, String email, String dni,
			Set<Acreditacion> acreditacions, Set<Acreditacion> acreditacions_1,
			Set<Acreditacion> acreditacions_2, Set<Acreditacion> acreditacions_3) {
		this.idAsistente = idAsistente;
		this.apellido = apellido;
		this.nombre = nombre;
		this.telefono = telefono;
		this.celular = celular;
		this.fax = fax;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.referencia = referencia;
		this.usuarioInsert = usuarioInsert;
		this.usuarioUpdate = usuarioUpdate;
		this.fechaInsert = fechaInsert;
		this.fechaUpdate = fechaUpdate;
		this.cargo = cargo;
		this.compania = compania;
		this.email = email;
		this.dni = dni;
		this.acreditacions = acreditacions;

	}

	public int getIdAsistente() {
		return this.idAsistente;
	}

	public void setIdAsistente(int idAsistente) {
		this.idAsistente = idAsistente;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Integer getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Integer referencia) {
		this.referencia = referencia;
	}

	public String getUsuarioInsert() {
		return this.usuarioInsert;
	}

	public void setUsuarioInsert(String usuarioInsert) {
		this.usuarioInsert = usuarioInsert;
	}

	public String getUsuarioUpdate() {
		return this.usuarioUpdate;
	}

	public void setUsuarioUpdate(String usuarioUpdate) {
		this.usuarioUpdate = usuarioUpdate;
	}

	public Date getFechaInsert() {
		return this.fechaInsert;
	}

	public void setFechaInsert(Date fechaInsert) {
		this.fechaInsert = fechaInsert;
	}

	public Date getFechaUpdate() {
		return this.fechaUpdate;
	}

	public void setFechaUpdate(Date fechaUpdate) {
		this.fechaUpdate = fechaUpdate;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombreCompleto() {
		return (this.nombre + " " + this.apellido);
	}

	public Set<Acreditacion> getAcreditacions() {
		return this.acreditacions;
	}

	public void setAcreditacions(Set<Acreditacion> acreditacions) {
		this.acreditacions = acreditacions;
	}

	public void insert(Usuario insert) throws RuntimeException, ConstraintViolationException {

		if (insert != null) {
			this.setUsuarioInsert(insert.getUserName());
		}
		AsistenteHome.getInstance().persist(this);
	}

	public static Asistente findByDni(String dni) throws RuntimeException {

		return AsistenteHome.getInstance().findByDni(dni);
	}
	
	public  void update(Usuario update) throws RuntimeException {

		if (update != null) {
			this.setUsuarioUpdate(update.getUserName());
		}
		AsistenteHome.getInstance().Update(this);
	}

}
